name = "payitforward-payment-scheduler"
main = "payment-scheduler.js"
compatibility_date = "2024-01-01"

# Cron triggers - run daily at midnight UTC
[triggers]
crons = ["0 0 * * *"]

# Environment variables
[vars]
API_URL = "https://your-backend-url.com/api"

# Secrets (set using: wrangler secret put API_SECRET)
# API_SECRET = "your-secret-key"

# Account configuration
account_id = "your-cloudflare-account-id"
workers_dev = true
